Repository benfred/py-spy, pull requests merged in 2025-07, with the labels that each got.

#768 make remoteprocess unwind feature optional
  Cargo.toml
Labels: enhancement

#739 Update pyproject.toml to support installing with latest uv
  pyproject.toml
Labels: enhancement

#747 Check "version", new name of "Py_GetVersion.version" since 3.12
  src/python_process_info.rs
Labels: enhancement

#751 Fix native stack merging for Python 3.12/3.13
  src/main.rs
  src/native_stack_trace.rs
  src/speedscope.rs
  src/stack_trace.rs
Labels: bug

#775 Test aarch64 in github actions
  .github/workflows/build.yml
  ci/update_python_test_versions.py
Labels: ci

#769 docs: use debug ephemeral containers
  README.md
Labels: documentation

#791 Add the Copy trait for python interpreter traits
  generate_bindings.py
  src/python_bindings/v3_11_0.rs
  src/python_bindings/v3_12_0.rs
  src/python_bindings/v3_7_0.rs
  src/python_data_access.rs
  src/python_interpreters.rs
Labels: enhancement

#738 Suggest visiting https://ui.perfetto.dev/ to view chrome traces
  src/main.rs
Labels: enhancement

#626 Page-align offset before calculating virtual addresses for ELF
  Cargo.lock
  Cargo.toml
  src/binary_parser.rs
Labels: bug
